name: Build and Push Docker Image

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Git commit timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest
            ${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:${{ env.TIMESTAMP }}
