name: Deploy Docker Image to Server

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Linux server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}        
          username: ${{ secrets.SERVER_USER }}    
          key: ${{ secrets.SERVER_SSH_KEY }}     
          port: 22
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/mleng_sayhi:latest
            CONTAINER=mleng_sayhi

            echo "Pulling image: $IMAGE"
            docker pull "$IMAGE"

            echo "Remove previous container if exists"
            docker rm -f "$CONTAINER" 2>/dev/null || true

            echo "Run container one-shot (writes file then exits)"
            docker run --name "$CONTAINER" --rm \
              -v /opt/assignment_outputs:/app/data \
              "$IMAGE"

            echo "Done. Check /opt/assignment_outputs on the server."
